# Generated by Django 3.2.16 on 2023-02-09 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urban', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urban',
            old_name='slug',
            new_name='slugUrban',
        ),
    ]
