# Generated by Django 3.2.16 on 2023-02-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urban', '0002_rename_slug_urban_slugurban'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urban',
            old_name='slugUrban',
            new_name='slug',
        ),
    ]
