# Generated by Django 3.2.16 on 2023-02-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban', '0003_rename_slugurban_urban_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='urban',
            name='showmap',
            field=models.BooleanField(default=True),
        ),
    ]
