# Generated by Django 3.2.16 on 2023-02-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='active_days',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='change_direction',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='fare_calculator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='go_app_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='leap_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='other_fares',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='public_notes',
            field=models.TextField(blank=True),
        ),
    ]
