# Generated by Django 3.2.16 on 2023-02-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_auto_20230209_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='urban',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
