# Generated by Django 3.2.16 on 2023-02-09 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_urban_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Urban',
        ),
    ]
