# Generated by Django 3.2.16 on 2023-02-19 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_auto_20230219_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='inbound',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='outbound',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
